export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';
export const FILTER = 'FILTER';

export const STATISTICS_FETCH_REQUEST = 'STATISTICS_FETCH_REQUEST';
export const STATISTICS_FETCH_SUCCESS = 'STATISTICS_FETCH_SUCCESS';
export const STATISTICS_FETCH_FAIL = 'STATISTICS_FETCH_FAIL';

export const EXPENSES_FETCH_REQUEST = 'EXPENSES_FETCH_REQUEST';
export const EXPENSES_FETCH_SUCCESS = 'EXPENSES_FETCH_SUCCESS';
export const EXPENSES_FETCH_FAIL = 'EXPENSES_FETCH_FAIL';
export const EXPENSES_ADD_FAIL = 'EXPENSES_ADD_FAIL';
export const EXPENSES_ADD_SUCCESS = 'EXPENSES_ADD_SUCCESS';

export const LOAN_ADD_REQUEST = 'LOAN_ADD_REQUEST';
export const LOAN_ADD_FAIL = 'LOAN_ADD_FAIL';
export const LOAN_ADD_SUCCESS = 'LOAN_ADD_SUCCESS';
export const LOAN_FETCH_SUCCESS = 'LOAN_FETCH_SUCCESS';
export const LOAN_FETCH_FAIL = 'LOAN_FETCH_FAIL';
export const LOAN_FETCH_REQUEST = 'LOAN_FETCH_REQUEST';
export const FILTER_LOAN = 'FILTER_LOAN';

export const LOAN_PAYMENT_ADD_REQUEST = 'LOAN_PAYMENT_ADD_REQUEST';
export const LOAN_PAYMENT_ADD_FAIL = 'LOAN_PAYMENT_ADD_FAIL';
export const LOAN_PAYMENT_ADD_SUCCESS = 'LOAN_PAYMENT_ADD_SUCCESS';
export const LOAN_PAYMENT_FETCH_SUCCESS = 'LOAN_PAYMENT_FETCH_SUCCESS';
export const LOAN_PAYMENT_FETCH_FAIL = 'LOAN_PAYMENT_FETCH_FAIL';
export const LOAN_PAYMENT_FETCH_REQUEST = 'LOAN_FETCH_REQUEST';

export const ROUTINA_FETCH_SUCCESS = 'ROUTINA_FETCH_SUCCESS';
export const ROUTINA_FETCH_FAIL = 'ROUTINA_FETCH_FAIL';
export const ROUTINA_FETCH_REQUEST = 'ROUTINA_FETCH_REQUEST';

export const PROFILE_SAVE_REQUEST = 'PROFILE_SAVE_REQUEST';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS';
export const PROFILE_SAVE_FAIL = 'PROFILE_SAVE_FAIL';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPADTE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPADTE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPADTE_FAIL';

export const CITY_FETCH_REQUEST = 'CITY_FETCH_REQUEST';
export const CITY_FETCH_SUCCESS = 'CITY_FETCH_SUCCESS';
export const CITY_FETCH_FAIL = 'CITY_FETCH_FAIL';
export const CITY_ADD_REQUEST = 'CITY_ADD_REQUEST';
export const CITY_ADD_SUCCESS = 'CITY_ADD_SUCCESS';
export const CITY_ADD_FAIL = 'CITY_ADD_FAIL';

export const PLAN_FETCH_REQUEST = 'PLAN_FETCH_REQUEST';
export const PLAN_FETCH_SUCCESS = 'PLAN_FETCH_SUCCESS';
export const PLAN_FETCH_FAIL = 'PLAN_FETCH_FAIL';
export const PLAN_ADD_REQUEST = 'PLAN_ADD_REQUEST';
export const PLAN_ADD_SUCCESS = 'PLAN_ADD_SUCCESS';
export const PLAN_ADD_FAIL = 'PLAN_ADD_FAIL';

export const USER_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USER_FETCH_FAIL = 'USERS_FETCH_FAIL';
export const USER_ADD_REQUEST = 'USERS_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
export const USER_ADD_FAIL = 'USERS_ADD_FAIL';

export const PAYMENT_FETCH_REQUEST = 'PAYMENT_FETCH_REQUEST';
export const PAYMENT_FETCH_SUCCESS = 'PAYMENT_FETCH_SUCCESS';
export const PAYMENT_FETCH_FAIL = 'PAYMENT_FETCH_FAIL';
export const PAYMENT_ADD_REQUEST = 'PAYMENT_ADD_REQUEST';
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS';
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL';

export const PROXY = 'http://178.128.144.72'; //'http://localhost:5000';
