export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const USER_LOADED= 'USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOG_OUT='LOG_OUT'
export const LOG_IN_SUCCESS='LOG_IN_SUCCESS'
export const LOG_IN_FAIL='LOG_IN_FAIL'
export const PROFILE_FETCH_REQUEST='PROFILE_FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS='PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL='PROFILE_FETCH_FAIL'
export const FILTER='FILTER'

export const LOAN_ADD_REQUEST="LOAN_ADD_REQUEST"
export const LOAN_ADD_FAIL= "LOAN_ADD_FAIL"
export const LOAN_ADD_SUCCESS ="LOAN_ADD_SUCCESS"
export const LOAN_FETCH_SUCCESS="LOAN_FETCH_SUCCESS"
export const LOAN_FETCH_FAIL="LOAN_FETCH_FAIL"
export const LOAN_FETCH_REQUEST= "LOAN_FETCH_REQUEST"
export const FILTER_LOAN='FILTER_LOAN'

export const PROFILE_SAVE_REQUEST='PROFILE_SAVE_REQUEST'
export const PROFILE_SAVE_SUCCESS='PROFILE_SAVE_SUCCESS'
export const PROFILE_SAVE_FAIL='PROFILE_SAVE_FAIL'
